<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <IsPackable>true</IsPackable>
    <PackageTags>aspire integration hosting azure apim api-management gateway cloud</PackageTags>
    <Description>Azure API Management resource types for Aspire.</Description>
    <NoWarn>$(NoWarn);AZPROVISION001;ASPIREAZURE003</NoWarn>
    <SuppressFinalPackageVersion>true</SuppressFinalPackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aspire.Hosting.Azure\Aspire.Hosting.Azure.csproj" />
    <PackageReference Include="Azure.Provisioning.ApiManagement" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Aspire.Hosting.Azure.Tests" />
  </ItemGroup>

</Project>
